"""String constants for the open-loop grasp state machine."""

IDLE = 'IDLE'
WAIT_PRE_TARGET = 'WAIT_PRE_TARGET'
PRE_OPEN_GRIPPER = 'PRE_OPEN_GRIPPER'
MOVE_PRE_GRASP = 'MOVE_PRE_GRASP'
MOVE_APPROACH_BLEND = 'MOVE_APPROACH_BLEND'
MOVE_GRASP = 'MOVE_GRASP'
CLOSE_GRIPPER = 'CLOSE_GRIPPER'
MOVE_LIFT = 'MOVE_LIFT'
MOVE_RETREAT = 'MOVE_RETREAT'
RETURN_INIT_POSE = 'RETURN_INIT_POSE'
RECOVER = 'RECOVER'

MAIN_FLOW = (
    WAIT_PRE_TARGET,
    PRE_OPEN_GRIPPER,
    MOVE_PRE_GRASP,
    MOVE_GRASP,
    CLOSE_GRIPPER,
    MOVE_LIFT,
    RETURN_INIT_POSE,
)
